### PR TITLE
Factor test data out of test module

### PR DESCRIPTION
**Pull request by zancas**
I renamed `tests.rs` to `tests/mod.rs` for reasons I am not entirely clear on this made it easier to use `mod` namespaces to organize test data.

Organizing test data was my primary motivation for this work.   I wanted to be able to easily read the test code in the `first-tests-later-mod.rs` file.  This solution worked for me.

While I was hacking this out @str4d (who was unaware I was poking about) updated the test data..   I add his update with a commit message pointing to the original commit.

### CODE REVIEW

**Comment by str4d** [comment]
Hey, this is a great refactor, thanks! It can't be merged as-is due to a conflict, and also because the `TestVector` structs need to be semantically separated like before. But I'll cherry-pick this onto my branch and tweak it appropriately 🙂

**Comment by zancas** [comment]
Great!  Thanks!  Will that be here:

https://github.com/str4d/librustzcash/tree/zcash-transaction-primitives

?

I have two other things to commit, and I'd like to PR them against the most convenient branch.

**Comment by zancas** [comment]
Ahh..   you mean you prefer each `fn test_..` to define its own `TestVector`?

**Comment by zancas** [comment]
@str4d , I will refactor again on top of your latest, with the `TestVector` structs (plural) held distinct with each test.  So that the code can be cleanly merged.

**Comment by zancas** [comment]
When you say the TestVector struct needs to be semantically separated, do you mean you want a separate struct for each test?

**Comment by zancas** [comment]
OK @str4d I refactored atop your latest, to remove the need for a cherry-pick.

I'm not exactly clear on whether the `TestVector` struct is defined optimally.

**Comment by str4d** [comment]
The branch this PR is targeting was merged upstream in https://github.com/zcash/librustzcash/pull/39, so this PR should probably be closed here and rebased / recreated on upstream master.

**Comment by zancas** [comment]
I'll put this on the TODO list.

**Comment by zancas** [comment]
I notice automated tests run when I update the PR against the @str4d fork.   I'll let them run, before possibly closing and re-opening against origin.

**Comment by zancas** [comment]
Alright, all checks passed....   closing an reopening against origin/master.

**Pull request closed without merging**
